name = "GriddedKernelMatrices"
uuid = "cf2c15de-87d3-40f9-b8fb-d9ceedc29f88"
version = "0.1.0"
authors = ["Chris Geoga <geoga@wisc.edu>"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[weakdeps]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LowRankApprox = "898213cb-b102-5a47-900c-97e73b919f73"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Vecchia = "8d73829f-f4b0-474a-9580-cecc8e084068"

[extensions]
GriddedKernelMatricesKrylovExt = ["Krylov"]
GriddedKernelMatricesVecchiaExt = ["Vecchia"]

[compat]
FFTW = "1"
LinearAlgebra = "1"
StaticArraysCore = "1"

[targets]
test = ["Test", "StaticArrays", "Krylov", "Vecchia", "LowRankApprox"]
